### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by sahni619** [nkaz001/sample-trading-bot#3]
Hi,

Thanks for this bot. While running this bot in testnet, I get below error message. Could you please help?

`INFO:root:WS Connected.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/sample-trading-bot/tradingbot/custom_strategy.py", line 60, in <module>
    run()
  File "/root/sample-trading-bot/tradingbot/custom_strategy.py", line 56, in run
    order_manager.run_loop()
  File "/root/sample-trading-bot/tradingbot/ordermanager.py", line 155, in run_loop
    ioloop.run_until_complete(start())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/sample-trading-bot/tradingbot/ordermanager.py", line 139, in start
    await self.place_orders()
  File "/root/sample-trading-bot/tradingbot/custom_strategy.py", line 23, in place_orders
    mid = (bid['price'][0] + ask['price'][0]) / 2.0
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/series.py", line 956, in __getitem__
    return self._values[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7efff4c3ee90>
ERROR:asyncio:Task was destroyed but it is pending!`

**Comment by nkaz001** [comment]
It seems there is no depth information. I think the callback `place_order` is called before the bot receives the depth information. Try to add a code to check if there is depth like `if len(bid['price']) == 0 or len(ask['price']) == 0: return` before calculating mid.
